// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2KcADS5VJfyG-n2SV5RDl83n8rBsE6Q',
    appId: '1:1047925796647:web:44d0406d5d4c1057864302',
    messagingSenderId: '1047925796647',
    projectId: 'ustaad-ai-app',
    authDomain: 'ustaad-ai-app.firebaseapp.com',
    storageBucket: 'ustaad-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHqOVo_CuSYqMrStrig9XVfKRN2HHpLA',
    appId: '1:1047925796647:android:307789d65d1d6532864302',
    messagingSenderId: '1047925796647',
    projectId: 'ustaad-ai-app',
    storageBucket: 'ustaad-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwrSCPbFnnF20X1aihh-Y9EAJUd7IglRU',
    appId: '1:1047925796647:ios:4c67a474c6a1e88c864302',
    messagingSenderId: '1047925796647',
    projectId: 'ustaad-ai-app',
    storageBucket: 'ustaad-ai-app.firebasestorage.app',
    androidClientId: '1047925796647-88k5nui6gpef4j5qnu45aifhk09p2vi6.apps.googleusercontent.com',
    iosClientId: '1047925796647-o3j947ocicr9cft6ljl5ola87rbrr7ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustaad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwrSCPbFnnF20X1aihh-Y9EAJUd7IglRU',
    appId: '1:1047925796647:ios:4c67a474c6a1e88c864302',
    messagingSenderId: '1047925796647',
    projectId: 'ustaad-ai-app',
    storageBucket: 'ustaad-ai-app.firebasestorage.app',
    androidClientId: '1047925796647-88k5nui6gpef4j5qnu45aifhk09p2vi6.apps.googleusercontent.com',
    iosClientId: '1047925796647-o3j947ocicr9cft6ljl5ola87rbrr7ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.ustaad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2KcADS5VJfyG-n2SV5RDl83n8rBsE6Q',
    appId: '1:1047925796647:web:b3517d68787db315864302',
    messagingSenderId: '1047925796647',
    projectId: 'ustaad-ai-app',
    authDomain: 'ustaad-ai-app.firebaseapp.com',
    storageBucket: 'ustaad-ai-app.firebasestorage.app',
  );

}